name: Release

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: run cake
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        target: Publish
      env: 
        nugetApiKey: ${{ secrets.nugetApiKey }}  
